version: '3'

services:
  pihole:
    build: .
    environment:
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
      - WEBPASSWORD=your_password_here
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d

  wireguard:
    image: indserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - SERVERURL=your_domain_or_ip  # Replace with your domain or IP
      - SERVERPORT=51820
      - PEERS=1  # Number of clients
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - wireguard_data:/etc/wireguard
    ports:
      - "51820:51820/udp"

volumes:
  pihole_data:
  dnsmasq_data:
  wireguard_data:
